# https://github.com/lowlighter/metrics
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jakerothstein
          template: classic
          base: header, activity, community, repositories, metadata
          config_padding: 6%
          config_timezone: America/Los_Angeles
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_calendar: yes

          
